language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 PACKAGE=tlapm2 DEPOPTS="*" EXTRA_DEPS=kaputt
  - OCAML_VERSION=4.04 PACKAGE=tlapm2 DEPOPTS="*" EXTRA_DEPS=kaputt
  - OCAML_VERSION=4.05 PACKAGE=tlapm2 DEPOPTS="*" EXTRA_DEPS=kaputt
  - OCAML_VERSION=4.07 PACKAGE=tlapm2 DEPOPTS="*" EXTRA_DEPS=kaputt
  - OCAML_VERSION=4.08 PACKAGE=tlapm2 DEPOPTS="*" EXTRA_DEPS=kaputt
os:
  - linux
